services:
  - type: web
    name: laravel-docker-app
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d2082g7diees7396ufq0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ego_inventory_db
      - key: DB_USERNAME
        value: ego_inventory_db_user
      - key: DB_PASSWORD
        value: VVSJ9lVCpRvWOkhCj8ku6nZxvI8HLxsM
