services:
  - type: web
    name: ego-inventory
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://jkdyinventory.shop
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d2082g7diees7396ufq0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ego_inventory_db
      - key: DB_USERNAME
        value: ego_inventory_db_user
      - key: DB_PASSWORD
        value: VVSJ9lVCpRvWOkhCj8ku6nZxvI8HLxsM
