<x-livewire.sales-form 
                        :customerSearch='$customerSearch' 
                        :productSearch='$productSearch' 
                        :products='$products' 
                        :productList='$productList'
                        :customers='$customers'
                        :saleList='$saleList' 
                        :sale='$sale'
                        />
